[
  {
    field_id: 772917,
    field_name: "ID агента",
    field_code: null,
    field_type: "text",
    values: [[Object]],
  },
  {
    field_id: 772067,
    field_name: "Фамилия Клиента",
    field_code: null,
    field_type: "text",
    values: [[Object]],
  },
  {
    field_id: 772069,
    field_name: "Имя клиента",
    field_code: null,
    field_type: "text",
    values: [[Object]],
  },
  {
    field_id: 772071,
    field_name: "Дата рождения",
    field_code: null,
    field_type: "date",
    values: [[Object]],
  },
  {
    field_id: 772073,
    field_name: "Регион",
    field_code: null,
    field_type: "text",
    values: [[Object]],
  },
  {
    field_id: 772075,
    field_name: "Телефон для связи",
    field_code: null,
    field_type: "text",
    values: [[Object]],
  },
  {
    field_id: 772077,
    field_name: "Предыдущй полис",
    field_code: null,
    field_type: "text",
    values: [[Object]],
  },
  {
    field_id: 772863,
    field_name: "Сумма остатка по кредиту",
    field_code: null,
    field_type: "text",
    values: [[Object]],
  },
  {
    field_id: 772867,
    field_name: "Банк по кредиту",
    field_code: null,
    field_type: "text",
    values: [[Object]],
  },
  {
    field_id: 772979,
    field_name: "Channel",
    field_code: null,
    field_type: "text",
    values: [[Object]],
  },
  {
    field_id: 772931,
    field_name: "Ответственный сотрудник",
    field_code: null,
    field_type: "select",
    values: [[Object]],
  },
  {
    field_id: 772919,
    field_name: "Дата создания",
    field_code: null,
    field_type: "date",
    values: [[Object]],
  },
  {
    field_id: 772921,
    field_name: "Дата статуса",
    field_code: null,
    field_type: "date",
    values: [[Object]],
  },
  {
    field_id: 772925,
    field_name: "ФИО клиента",
    field_code: null,
    field_type: "text",
    values: [[Object]],
  },
  {
    field_id: 772923,
    field_name: "Стоимость полиса",
    field_code: null,
    field_type: "numeric",
    values: [[Object]],
  },
  {
    field_id: 772927,
    field_name: "ОСЗ",
    field_code: null,
    field_type: "numeric",
    values: [[Object]],
  },
  {
    field_id: 772933,
    field_name: "Тип полиса",
    field_code: null,
    field_type: "multiselect",
    values: [[Object], [Object], [Object]],
  },
  {
    field_id: 772935,
    field_name: "Объект",
    field_code: null,
    field_type: "select",
    values: [[Object]],
  },
  {
    field_id: 772937,
    field_name: "Комментарий при отказе",
    field_code: null,
    field_type: "textarea",
    values: [[Object]],
  },
  {
    field_id: 772939,
    field_name: "Номер полиса",
    field_code: null,
    field_type: "text",
    values: [[Object]],
  },
  {
    field_id: 772941,
    field_name: "Номер телефона",
    field_code: null,
    field_type: "text",
    values: [[Object]],
  },
  {
    field_id: 772943,
    field_name: "Банк",
    field_code: null,
    field_type: "text",
    values: [[Object]],
  },
  {
    field_id: 772945,
    field_name: "СК",
    field_code: null,
    field_type: "text",
    values: [[Object]],
  },
  {
    field_id: 772947,
    field_name: "КВ Пампаду",
    field_code: null,
    field_type: "numeric",
    values: [[Object]],
  },
  {
    field_id: 772949,
    field_name: "КВ агента",
    field_code: null,
    field_type: "numeric",
    values: [[Object]],
  },
  {
    field_id: 773425,
    field_name: "ID карточки",
    field_code: null,
    field_type: "text",
    values: [[Object]],
  },
  {
    field_id: 774175,
    field_name: "Причина закрытия заявки",
    field_code: null,
    field_type: "select",
    values: [[Object]],
  },
  {
    field_id: 774113,
    field_name: "ID куратора",
    field_code: null,
    field_type: "text",
    values: [[Object]],
  },
  {
    field_id: 774173,
    field_name: "Скидка за счет КВ",
    field_code: null,
    field_type: "text",
    values: [[Object]],
  },
];
