module.exports = {
  ID: "id",
  SURNAME: "familya",
  NAME: "name",
  DATE_BIRTHDAY: "godrojdenya",
  REGION: "region",
  PHONE: "phone",
  PREVIOUS_POLIS: "pred_polis",
  BALANCE_AMOUNT: "summa_ostatka",
  BANK_ON_LOAN: "bank_po_kreditu",
  CHANEL: "chanel",
  RESPONSIBLE_EMPLOYEE: "otvet_sotrudnik",
  CREATED_AT: "data_sozdanya",
  CALL_AT: "data_zvonka",
  STATUS_AT: "data_statusa",
  FULL_NAME_CLIENT: "fio_client",
  POLIS_PRICE: "stoimost_polisa",
  OSZ: "osz",
  DISCOUNT_DUE_TO_CV: "skidka_za_schet_cv",
  POLIS_TYPE: "tip_polisa",
  OBJECT: "object",
  COMMENT: "commentari",
  POLIS_NUMBER: "nomer_polisa",
  PHONE_NUMBER: "nomer_telefona",
  BANK: "bank",
  CK: "ck",
  KV_PAMPADU: "kv_pompadu",
  KV_AGENT: "kv_agent",
  KV_KURATOR: "ID куратора",
  LEAD_ID: "id_lead",
  LEAD_LINK: "id_link",
};
